# Generated by Django 4.2.29 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0002_analysissession_result_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysissession',
            name='summary_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
