# Generated by Codex on 2026-03-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("optimizer", "0003_analysissession_completed_at_and_more"),
        ("optimizer", "0003_userprofile"),
    ]

    operations = []
