# Generated by Django 4.2.29 on 2026-05-11 09:30

from django.db import migrations, models


def seed_roles(apps, schema_editor):
    """
    Back-fill roles for all existing UserProfile rows:
      superuser → admin
      staff     → editor
      everyone else → viewer  (default; no change needed but explicit for clarity)
    """
    UserProfile = apps.get_model("optimizer", "UserProfile")
    for profile in UserProfile.objects.select_related("user").all():
        if profile.user.is_superuser:
            profile.role = "admin"
        elif profile.user.is_staff:
            profile.role = "editor"
        else:
            profile.role = "viewer"
        profile.save(update_fields=["role"])


def reverse_seed_roles(apps, schema_editor):
    pass  # no meaningful reverse; field will be removed by RemoveField


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer', '0008_add_product_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('editor', 'Editor'), ('viewer', 'Viewer')],
                db_index=True,
                default='viewer',
                max_length=10,
            ),
        ),
        migrations.RunPython(seed_roles, reverse_code=reverse_seed_roles),
    ]
